import { useAppContext } from "$components/context/Context";
import axios from "axios";
import type { NextPage } from "next";
import Head from "next/head";
import useSWR from "swr";

const Home: NextPage = () => {
  const { token } = useAppContext();
  const fetcher = () => {};
  const { data, error } = useSWR("/api/user", fetcher);

  if (!token) return <div>No token</div>;

  return (
    <div>
      <Head>
        <title>Tu dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="m-auto mx-auto flex space-x-4"></div>
    </div>
  );
};

export default Home;
